name: 'Report a documentation issue'
description: Report an issue with the Confluent plugin documentation.
title: 'Docs: '
labels:
  - 'documentation'
  - 'needs triage'
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new documentation issue, is this something you can help us with? Your contributions are welcomed and appreciated.

        If you are reporting a documentation request rather than a bug, please open a [feature request issue](https://github.com/confluentinc/intellij/issues/new/choose) instead.
  - type: markdown
    attributes:
      value: Thank you for helping us update our docs!
  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: 'Example: There is incorrect or stale information about configuring a Kafka connection.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://docs.confluent.io/...'
    validations:
      required: false
