config.name.default=Kafka
connection.success=Connected to Kafka
toolwindow.title=Kafka
# Text when no connections
toolwindow.empty.text=No Kafka monitoring connections are set.
toolwindow.empty.link=Add new
toolwindow.empty.secondaryText=connection.
open.settings.action.text=Settings
open.settings.action.description=Open Kafka connections settings
open.url=Open In Browser
show.internal.topic=Show Internal Topics
show.internal.topic.hint=Show internal topics
show.full.topic.config=Show Full Config
show.full.topic.config.hint=Show full config
topic.not.found=Topic {0} is not found
topic.tab.configs=Configuration
topic.tab.partitions=Partitions
kafka.support.is.limited=Kafka support is limited
kafka.support.is.limited.helper=\
<p>Supported features:</p>\
<ul>\
<li>Topic table</li>\
<li>Topic detailed info</li>\
<li>Topic partition table</li>\
<li>Consumer group table</li>\
</ul><br>\
This list will be extended in the next releases.
settings.properties=Properties:
settings.properties.file=Properties file:
settings.properties.file.browse=Kafka Properties File
settings.property.source=Properties source:
settings.property.source.direct=Field
settings.property.source.file=File
create.producer.action.title=Add producer
create.consumer.action.title=Add consumer
kafka.producer.action.produce.title=Produce
action.consume.start.title=Start Consuming
action.consume.stop.title=Stop Consuming
record.headers.label=Headers:
producer.idempotence.label=Idempotence
produce.to.topic=Produce to Topic
consume.from.topic=Consume from Topic
action.clear.output=Clear Output
action.save.preset=Save Preset to Favorites
action.remove.preset=Remove Preset from Favorites

# Producer
producer.title.data=Data
producer.topics=Topic:
producer.key=Key:
producer.value=Value:
producer.title.options=Options
producer.forcePartition=Force partition:
producer.compression=Compression:
producer.asks=Asks:
producer.preset.apply=Apply Preset to Settings
producer.error.topic.empty.title=Producer Error
producer.error.topic.empty=Topic not selected

# Consumer editor
consumer.error.topic.empty.title=Consumer Error
consumer.error.topic.empty=Topic not selected
label.filter.key=Key:
label.filter.value=Value:
label.filter.head.key=Header key:
label.filter.head.value=Header value:
settings.label.topics=Topic:
settings.title.format=Format
settings.format.key=Key:
settings.format.value=Value:
settings.title.range.filters=Range and Filters
settings.filters.from=Start from:
settings.filters.limit=Limit:
settings.filter=Filter:
settings.title.partitions=Partitions
settings.partitions=Partitions:
toggle.presets=Presets
toggle.settings=Settings
toggle.data=Data
toggle.details=Details

# FieldType
field.type.json=JSON
field.type.string=String
field.type.long=Long
field.type.double=Double
field.type.float=Float
field.type.base64=Bytes (Base64)
field.type.null=None

# ConsumerLimitType
consumer.limit.type.none=None
consumer.limit.type.topicRecords=Topic records number
consumer.limit.type.date=Date
consumer.limit.type.topicMaxSize=Topic max size
consumer.limit.type.partitionRecords=Partition records number
consumer.limit.type.partitionMaxSize=Partition max size

# ConsumerStartType
consumer.start.type.now=Now
consumer.start.type.lastHour=Last hour
consumer.start.type.today=Today
consumer.start.type.yesterday=Yesterday
consumer.start.type.specificDate=Specific date
consumer.start.type.beginning=From the beginning
consumer.start.type.consumerGroup=Consumer group
consumer.start.type.latestOffsetMinusX=Latest offset minus X
consumer.start.type.offset=Offset

# ConsumerFilterType
consumer.filter.type.none=None
consumer.filter.type.contains=Contains
consumer.filter.type.notContains=Not contains
consumer.filter.type.regexp=RegExp

# Consumer record details
consumer.record.data=Data
consumer.record.headers=Headers:
consumer.record.topic=Topic:
consumer.record.key=Key:
consumer.record.value=Value:
consumer.record.partition=Partition:
consumer.record.offset=Offset:
consumer.record.timestamp=Timestamp:
consumer.record.keysize=Key size:
consumer.record.valuesize=Value size:
property.file.is.not.found=Kafka property is not found {0}
error.start.consumer=Consumer error
producer.wrong.partition=Wrong partition {0} for topic {1}
kafka.producer.error=Producer Error