config.name.default=Kafka
connection.success=Connected to Kafka
toolwindow.title=Kafka
# Text when no connections
toolwindow.empty.text=No Kafka monitoring connections are set.
toolwindow.empty.link=Add new
toolwindow.empty.secondaryText=connection.
open.settings.action.text=Settings
open.settings.action.description=Open Kafka connections settings
open.url=Open In Browser
show.internal.topic=Show Internal Topics
show.internal.topic.hint=Show internal topics
show.full.topic.config=Show Full Config
show.full.topic.config.hint=Show full config
topic.not.found=Topic {0} is not found
topic.tab.configs=Configuration
topic.tab.partitions=Partitions
kafka.support.is.limited=Kafka support is limited
kafka.support.is.limited.helper=\
<p>Supported features:</p>\
<ul>\
<li>Topic table</li>\
<li>Topic detailed info</li>\
<li>Topic partition table</li>\
<li>Consumer group table</li>\
</ul><br>\
This list will be extended in the next releases.
settings.properties=Properties:
create.producer.action.title=Producer
create.consumer.action.title=Consumer
kafka.producer.action.produce.title=Produce
action.consume.start.title=Start consume
action.consume.stop.title=Stop
record.headers.label=Headers
producer.idempotence.label=Idempotence
produce.to.topic=Produce to Topic
consume.from.topic=Consume from Topic
action.clear.output=Clear Output

# Producer
producer.title.data=Data
producer.topics=Topics:
producer.key=Key:
producer.value=Value:
producer.title.options=Options
producer.forcePartition=Force partition:
producer.compression=Compression:
producer.asks=Acks:
consumer.error.topic.empty=Topic is empty